---
title: 'Głębokie sieci neuronowe -- projekt'
author: 'Tomasz Górecki'
date: 'Ostatnia aktualizacja: `r format(Sys.Date(), "%d.%m.%Y")`'
output: pdf_document
---

## Opis zbioru danych
Projekt dotyczy rozpoznawania kształtów w zbiorze Fashion MNIST. Zbiór ten składa się z 70 000 (60 000 w zbiorze uczącym i 10 000 w zbiorze testowym) czarno-białych obrazków należących do 10 kategorii. Każdy obrazek przedstawia jedno z 10 ubrań (z asortymentu Zalando) w stosunkowo słabej rozdzielczości 28x28 pikseli. Na poniższym rysunku przedstawionych jest 25 pierwszych obrazków ze zbioru uczącego.

```{r echo=FALSE}
library(keras)
fashion_mnist <- dataset_fashion_mnist()
c(train_images, train_labels) %<-% fashion_mnist$train
c(test_images, test_labels) %<-% fashion_mnist$test
train_images <- train_images / 255
test_images <- test_images / 255
class_names = c('T-shirt/top',
                'Trouser',
                'Pullover',
                'Dress',
                'Coat', 
                'Sandal',
                'Shirt',
                'Sneaker',
                'Bag',
                'Ankle boot')
par(mfcol = c(5, 5))
par(mar = c(0, 0, 1.5, 0), xaxs = 'i', yaxs = 'i')
for (i in 1:25) { 
  img <- train_images[i, , ]
  img <- t(apply(img, 2, rev)) 
  image(1:28, 1:28, img, col = gray((0:255)/255), xaxt = 'n', yaxt = 'n',
        main = paste(class_names[train_labels[i] + 1]))
}
```

Każdy piksel ma skojarzoną z nim liczbę, która określa natężenie koloru (większa wartość oznacza ciemniejszy piksel). Zmienna ta przyjmuje wartości od 0 do 255. Zbiór uczący ma 785 kolumn ($28 \times 28 = 784$ piksele oraz etykietę klasy). Więcej informacji o zbiorze danych można znaleźć na stronie [Kaggle](https://www.kaggle.com/zalando-research/fashionmnist). Zbiór można załadować używając funkcji `r kableExtra::text_spec("dataset_fashion_mnist()", color = "blue")` z biblioteki `r kableExtra::text_spec("keras", color = "blue")`.

## Opis zadania
Państwa zadaniem jest skonstruowanie głębokiej sieci neuronowej (minimum trzy warstwy), która będzie klasyfikowała elementy zbioru testowego. Sieć ma być nauczona jedynie na zbiorze uczącym. Miarą jakości rozwiazania jest procent poprawnej klasyfikacji, który powinien przekroczyć 85% na biorze testowym. Najlepsze obecnie rozwiązania dla tego zbioru danych osiągają ponad 93% skuteczność.

## Raportowanie
Oczekuję przesłania do mnie na adres `r kableExtra::text_spec("tomasz.gorecki@amu.edu.pl", color = "blue")` kodów Państwa rozwiązania w R lub Python. W kodzie musi znaleźć się:

1. Wczytanie i przygotowanie danych.
2. Definicja modelu.
3. Wyuczenie modelu (minimum 50 epok) na zbiorze uczącym.
4. Wizualne przedstawienie procesu uczenia.
5. Pokazanie skuteczności modelu na zbiorze testowym.
6. Przestawienie wyników w postaci macierzy przynależności na zbiorze testowym.